version: "3"
services:
    server:
        container_name: joyuriz-server
        build:
            dockerfile: Dockerfile
            context: ./server
        volumes:
            - ./server/:/app
            - /node_modules
        environment: 
            - NODE_PATH=src
            - PORT=443
            - DB_HOST=joyuirz-db
            - DB=test
        networks:
            - backend
        depends_on:
            - mongo
        ports:
            - "443:443"
    mongo:
        container_name: joyuriz-db
        image: mongo
        volumes:
            - data:/data/DB
        ports:
            - "27017:27017"
        networks:
            - backend
    flask:
        container_name: joyuriz-api
        build:
            dockerfile: Dockerfile
            context: ./flask
        ports:
            - "5000:5000"
        networks:
            - backend
        depends_on:
            - server
        volumes:
            - ./flask/:/app
networks:
    backend:
        driver: bridge
volumes:
    data:
        driver: local