spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  redis:
    host: ${REDIS_IP}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
api:
  ip: ${API_IP}
  port: ${API_PORT}
  method: ${API_METHOD}

web:
  ip: ${WEB_IP}
  port: ${WEB_PORT}
  method: ${WEB_METHOD}

---
logging:
  level:
    root: info

server:
  port: 8080
spring:
  config:
    activate:
      on-profile: prod
