spring:
  profiles:
    active: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

api:
  ip: ${API_IP}
  port: ${API_PORT}
  method: ${API_METHOD}

web:
  ip: ${WEB_IP}
  port: ${WEB_PORT}
  method: ${WEB_METHOD}


---
server:
  port: 8080

logging:
  level:
    root: info
spring:
  config:
    activate:
      on-profile: local
---

logging:
  level:
    root: info

server:
  port: 443
  ssl:
    enabled: true
    key-store: cert/keystore.p12
    key-store-password: 20181029
    key-store-type: PKCS12
    key-alias: bns-ssl

spring:
  config:
    activate:
      on-profile: prod