name: spring-gateway

on:
  create:
    tags:
      - v*
  workflow_dispatch:
  
jobs:
  jar:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -  
        name: Setup Java JDK
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 11
          distribution: adopt
      - 
        name: Add +x permission
        working-directory: server2
        run: chmod +x gradlew
      - 
        name: Gradle Build
        working-directory: server2
        run: ./gradlew clean build
      -
        name: Move app file
        working-directory: server2
        run: mv ./build/libs/joyuriz*.jar ./app.jar
      - 
        name: Upload jar file to Artifact
        uses: actions/upload-artifact@master
        with:
          name: run
          path: ./server2/app.jar
          retention-days: 7
          
  qemu-build:
    needs: jar
    runs-on: self-hosted
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Download app from Artifact
        uses: actions/download-artifact@v1
        with:
          name: run
      - 
        name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - 
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      -
        name: Set up Docker Context
        run: docker context create multi-arch-builder
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: multi-arch-builder
      - 
        name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: test
        run: mv run server2/
      -
        working-directory: server2
        name: Docker Build
        run: docker buildx build --platform linux/arm64,linux/amd64 -f action.Dockerfile -t inerplat/joyuriz-springboot:${{ steps.vars.outputs.tag }} --push .
